const POMODORO_STATES = {
  WORK: 'work',
  REST: 'rest'
}
const STATES = {
  STARTED: 'started',
  STOPPED: 'stopped',
  PAUSED: 'paused'
}
const WORKING_TIME_LENGTH_IN_MINUTES = 25
const WORKING_TIME_LENGTH_IN_SECONDS = 10
const RESTING_TIME_LENGTH_IN_MINUTES = 0
const COLUMNS = 3
export default {
  POMODORO_STATES,
  WORKING_TIME_LENGTH_IN_MINUTES,
  RESTING_TIME_LENGTH_IN_MINUTES,
  WORKING_TIME_LENGTH_IN_SECONDS,
  STATES,
  COLUMNS
}
